### ISSUE TITLE
Multiple upgrades in a row cause Highway to crash

### ISSUE THREAD

**Issue by LeshM** [soomla/unity3d-store#468]
Caused by: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@2eeb1a87 rejected from java.util.concurrent.ThreadPoolExecutor@27999db4[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 135]
            at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
            at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
            at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
            at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:590)
            at com.soomla.highway.HighwayUtils.asyncTaskExecute(HighwayUtils.java:78)
            at com.soomla.highway.SoomlaHighway.sendGeneratedEvent(SoomlaHighway.java:141)
            at com.soomla.highway.SoomlaHighway.access$100(SoomlaHighway.java:41)
            at com.soomla.highway.SoomlaHighway$1.run(SoomlaHighway.java:123)
            at java.lang.Thread.run(Thread.java:818)

**Comment by refaelos** [comment]
Are you using the latest version of Highway?

**Comment by LeshM** [comment]
I'm using version 1.3.12, where can I check if it's the latest version?

Omer Leshem @ Round Robin LTD.

+972-50-869-1763 | RndRobin.com <http://rndrobin.com/>

**Comment by refaelos** [comment]
The error is in HW. Open the SOOMLA settings panel and let me know what versions you see there.

**Comment by LeshM** [comment]
[image: Untitled.png]

Omer Leshem @ Round Robin LTD.

+972-50-869-1763 | RndRobin.com <http://rndrobin.com/>

**Comment by refaelos** [comment]
put the image again ;)

**Comment by LeshM** [comment]
Sorry, I replied from my inbox.
Here's my versions:

Core: 1.0.6
Highway: 1.3.12
LevelUp: 1.0.11
Profile: 2.0.8
Store: 1.7.15

**Comment by refaelos** [comment]
There are new versions of almost everything. Can you download again and test? A lost of bug fixes went through the river ;)

http://library.soom.la/fetch/unity3d-grow/latest?cf=direct

**Comment by LeshM** [comment]
I will do that right away.
Is there a way to check if I have the latest version? So I wouldn't need to
bother you?

**Comment by refaelos** [comment]
Not at the moment... but we're working on it.
