### ISSUE TITLE
The game is Crashing

### ISSUE THREAD

**Issue by NerminShawkat** [soomla/unity3d-store#473]
the game crashed when i purchased a currency pack. when i uninstalled and reinstalled it, it crashed when i opened it 
note: I'm using a test account and I checked test purchases 

error { java.lang.IllegalArgumentException: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
at com.soomla.store.billing.google.Security.generatePublicKey(Security.java:88)
at com.soomla.store.billing.google.Security.verifyPurchase(Security.java:68)
at com.soomla.store.billing.google.GoogleIabHelper.queryPurchases(GoogleIabHelper.java:573)
at com.soomla.store.billing.google.GoogleIabHelper.restorePurchases(GoogleIabHelper.java:609)
at com.soomla.store.billing.google.GoogleIabHelper.access$500(GoogleIabHelper.java:56)
at com.soomla.store.billing.google.GoogleIabHelper$2.run(GoogleIabHelper.java:365)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.security.spec.InvalidKeySpecException: java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:143)
at com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic(OpenSSLRSAKeyFactory.java:47)
at java.security.KeyFactory.generatePublic(KeyFactory.java:172)
at com.soomla.store.billing.google.Security.generatePublicKey(Security.java:83)
... 6 more
Caused by: java.lang.RuntimeException: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long
at com.android.org.conscrypt.NativeCrypto.d2i_PUBKEY(Native Method)
at com.android.org.conscrypt.OpenSSLKey.getPublicKey(OpenSSLKey.java:141)
... 9 more
}

**Comment by refaelos** [comment]
It'll be best for you to ask questions at http://answers.soom.la

**Comment by NerminShawkat** [comment]
Thank you .. I was using a wrong public key .. It's working now
