### ISSUE TITLE
Crash on some devices

### ISSUE THREAD

**Issue by JEOptimal** [soomla/unity3d-store#489]
Hi,

We see this crash reported by a few devices(it's our most frequent crash). It occurs maybe once in a couple of thousand players.

Caused by: java.lang.NullPointerException
	at com.soomla.store.billing.google.GoogleIabHelper.queryPurchases(GoogleIabHelper.java:543)
	at com.soomla.store.billing.google.GoogleIabHelper.restorePurchases(GoogleIabHelper.java:609)
	at com.soomla.store.billing.google.GoogleIabHelper.access$500(GoogleIabHelper.java:56)
	at com.soomla.store.billing.google.GoogleIabHelper$2.run(GoogleIabHelper.java:365)
	at java.lang.Thread.run(Thread.java:838)

Is it because some incorrect way of accessing soomla?

**Comment by WinYao** [comment]
I have the same problem...

**Comment by vedi** [comment]
@JEOptimal, @WinYao, what a version of Soomla Store do you use?

**Comment by WinYao** [comment]
@vedi thank you, after I replaced GrowUltimate(version 14day ago), the problem has been resolved.
i'm a newbie of soomla
how to properly upgrade soomla plugin in already project
just delete all of soomla folder and import?
thanks!!

**Comment by vedi** [comment]
@WinYao,
> just delete all of soomla folder and import?

It's the best way, but there is also stuff in Plugins folder. And sometime it's hard to get what the files are Soomla's one. 
You can try just import new package. In the most cases it should work well.

**Comment by JEOptimal** [comment]
We're using Core Version 1.0.8 and Store Version 1.8.1 (build 1).

This is nothing we can reproduce but we can see the stack traces on our google developer console. So a few users are experiencing this issue. It's approx. 7.2 reports per 10 000 users. So maybe not that much. But if it's something that can be fixed it would still be good.
