### ISSUE TITLE
Android crash with KeyValueStorage - related to Keeva?

### ISSUE THREAD

**Issue by crunchbury** [soomla/unity3d-store#548]
Hi,
I'm getting a crash whenever I try and access KeyValueStorage. The crash looks related to Keeva but I can't quite tell. It is likely a manifest issue, but I don't know where to begin with solving this. Any idea?

```
08-17 09:05:33.465: I/Unity(22643): AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
08-17 09:05:33.465: I/Unity(22643): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
08-17 09:05:33.465: I/Unity(22643): 	at com.soomla.keeva.Keeva.<init>(Keeva.java:44)
08-17 09:05:33.465: I/Unity(22643): 	at com.soomla.data.KeyValueStorage.<init>(KeyValueStorage.java:178)
08-17 09:05:33.465: I/Unity(22643): 	at com.soomla.data.KeyValueStorage.getDefaultStorage(KeyValueStorage.java:160)
08-17 09:05:33.465: I/Unity(22643): 	at com.soomla.data.KeyValueStorage.getValue(KeyValueStorage.java:42)
08-17 09:05:33.465: I/Unity(22643): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-17 09:05:33.465: I/Unity(22643): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)
08-17 09:05:33.465: I/Unity(22643): 	at com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
08-17 09:05:33.465: I/Unity(22643): 	at android.os.Handler.dispatchMessage(Handler.java:98)
08-17 09:05:33.465: I/Unity(22643): 	at android.os.Looper.loop(Looper.java:148)
08-17 09:05:33.465: I/Unity(22643): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
08-17 09:05:33.465: I/Unity(22643):   at UnityEngine.AndroidJNISafe.CheckException () [0x00085]
```

**Comment by crunchbury** [comment]
One interesting note that may or may not be related is that I have an identical AndroidManifest.xml file in both /Plugins/Android/Soomla and /Plugins/Android/SoomlaShared.

```
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="com.soomla.SoomlaApp">
    <application/>
    <uses-sdk android:minSdkVersion="9" />
</manifest>
```

**Comment by crunchbury** [comment]
Ended up having to get professional help to solve this. From some combination of plug-ins, my primary AndroidManifest.xml ended up with this line:

`<application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="false">`

This lacked a name attribute which lead to the null context error. I changed it to the following and things are working:
`<application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="false" android:name="com.soomla.SoomlaApp">`
