### ISSUE TITLE
Crash on some android devices

### ISSUE THREAD

**Issue by Yichen525** [soomla/unity3d-store#556]
We run into some crashes on android devices:
1.  
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.soomla.store.billing.IabInventory.getAllQueriedSkus(boolean)' on a null object reference
       at com.soomla.store.billing.google.GooglePlayIabService$FetchSkusDetailsFinishedListener.onFetchSkusDetailsFinished(GooglePlayIabService.java:435)
       at com.soomla.store.billing.IabHelper$4.run(IabHelper.java:354)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:7007)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)

2.
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Bundle com.android.vending.billing.IInAppBillingService.getSkuDetails(int, java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
       at com.soomla.store.billing.google.GoogleIabHelper.querySkuDetailsChunk(GoogleIabHelper.java:694)
       at com.soomla.store.billing.google.GoogleIabHelper.querySkuDetails(GoogleIabHelper.java:671)
       at com.soomla.store.billing.google.GoogleIabHelper.fetchSkusDetails(GoogleIabHelper.java:520)
       at com.soomla.store.billing.google.GoogleIabHelper.access$900(GoogleIabHelper.java:56)
       at com.soomla.store.billing.google.GoogleIabHelper$3.run(GoogleIabHelper.java:390)
       at java.lang.Thread.run(Thread.java:818)

Any idea how to resolve the problems?

**Comment by khld85** [comment]
Hi
I'm getting the same problem
