### ISSUE TITLE
java.lang.nullPointException:Attmpt to invoke interface method‘boolean Java.until.list.isEmpty  when  initialize()’on a null object refrence 

### ISSUE THREAD

**Issue by MLprogram** [soomla/unity3d-store#559]
I use  bazaar sdk.report nullpointException when Initialize . 

I/Unity   ( 8933): AndroidJavaException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference

I/Unity   ( 8933): java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference

I/Unity   ( 8933): 	at com.soomla.store.billing.bazaar.BazaarIabHelper.startSetupInner(BazaarIabHelper.java:127)

I/Unity   ( 8933): 	at com.soomla.store.billing.IabHelper.startSetup(IabHelper.java:75)

I/Unity   ( 8933): 	at com.soomla.store.billing.bazaar.BazaarIabService.startIabHelper(BazaarIabService.java:210)

I/Unity   ( 8933): 	at com.soomla.store.billing.bazaar.BazaarIabService.initializeBillingService(BazaarIabService.java:54)

I/Unity   ( 8933): 	at com.soomla.store.SoomlaStore.restoreTransactions(SoomlaStore.java:166)

I/Unity   ( 8933): 	at com.soomla.store.SoomlaStore.refreshInventory(SoomlaStore.java:307)

I/Unity   ( 8933): 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

I/Unity   ( 8933): 	at com.unity3d.player.UnityPlayer.a(Unknown Source)

I/Unity   ( 8933): 	at com.unity3d.player.UnityPlayer$b.run(Unknown Source)

I/Unity   ( 8933):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] i

**Comment by selezen88** [comment]
Ive got the same issue. Have anyone found the solution?
