### ISSUE TITLE
crash on android devices somehow

### ISSUE THREAD

**Issue by Jason-Zy** [soomla/unity3d-store#569]
19211-08 15:42:30.228 14528 14723 I UnityIAP: getSkuDetails() failed: 6:Error
--
19311-08 15:42:30.229 14528 14723 I UnityIAP: onQueryInventoryFinished: false
19411-08 15:42:30.229 14528 14723 I UnityIAP: Error refreshing inventory (querying prices of items). (response: 6:Error)
19511-08 15:42:30.229 14528 14723 I UnityIAP: Failed to Query inventory. UnityIAP will automatically retry in 300000ms
19611-08 15:42:30.229 14528 14723 I UnityIAP: QueryInventory: 11
19711-08 15:42:30.229 14528 14723 I UnityIAP: invoking callback
19811-08 15:42:30.229 14528 14723 I UnityIAP: Querying owned items, item type: inapp
19911-08 15:42:30.229 14528 14723 I UnityIAP: Package name: com.windplay.globalwar
20011-08 15:42:30.229 14528 14723 I UnityIAP: Calling getPurchases with continuation token: null
20111-08 15:42:30.231 14528 14723 I UnityIAP: Owned items response: 0
20211-08 15:42:30.231 14528 14723 I UnityIAP: Continuation token: null
20311-08 15:42:30.236 14528 17115 I UnityIAP: invoking callback
204--------- beginning of crash
20511-08 15:42:30.236 14528 14723 E AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
20611-08 15:42:30.236 14528 14723 E AndroidRuntime: Process: com.windplay.globalwar, PID: 14528
20711-08 15:42:30.236 14528 14723 _E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.util.Map com.unity.purchasing.googleplay.Inventory.mSkuMap' on a null object reference_
20811-08 15:42:30.236 14528 14723 E AndroidRuntime: at com.unity.purchasing.googleplay.GooglePlayPurchasing.NotifyUnityOfProducts(GooglePlayPurchasing.java:589)
20911-08 15:42:30.236 14528 14723 E AndroidRuntime: at com.unity.purchasing.googleplay.GooglePlayPurchasing.access$400(GooglePlayPurchasing.java:44)
21011-08 15:42:30.236 14528 14723 E AndroidRuntime: at com.unity.purchasing.googleplay.GooglePlayPurchasing$4.workWith(GooglePlayPurchasing.java:524)
21111-08 15:42:30.236 14528 14723 E AndroidRuntime: at com.unity.purchasing.googleplay.BillingServiceManager$2.run(BillingServiceManager.java:146)
21211-08 15:42:30.236 14528 14723 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
21311-08 15:42:30.236 14528 14723 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
21411-08 15:42:30.236 14528 14723 E AndroidRuntime: at java.lang.Thread.run(Thread.java:919)

**Comment by Jason-Zy** [comment]
unity 2019.1.14, iap 1.22.0
